# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Load the dataset
EHMS = pd.read_csv('../../WUSTL-EHMS/wustl-ehms-2020.csv')
df = pd.DataFrame(EHMS)

# Define the columns to consider
columns_to_consider = ['Sport', 'SrcLoad', 'DstLoad', 'SIntPkt', 'DIntPkt', 'SrcJitter', 'DstJitter', 'Dur', 'Load', 'Rate', 'SrcMac', 
                       'Packet_num', 'Temp', 'SpO2', 'Pulse_Rate', 'SYS', 'DIA', 'Heart_rate', 'Resp_Rate', 'ST']

# Filter the dataset with the specified columns
df_filtered = df[columns_to_consider]

# Select only the categorical columns to apply One-Hot Encoding to
categorical_columns = df_filtered.select_dtypes(include=['object']).columns
print("Categorical Columns:", categorical_columns)

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the categorical data
encoded_data = encoder.fit_transform(df_filtered[categorical_columns])

# Get the feature names generated by the One-Hot Encoder
encoded_feature_names = encoder.get_feature_names_out(categorical_columns)

# Initialize the dictionary to hold the feature names and their One-Hot encodings
encoding_dict = {}

# Create a DataFrame with the encoded data
encoded_df = pd.DataFrame(encoded_data, columns=encoded_feature_names)

# For each categorical column, associate the value and its One-Hot encoded vector
for column in categorical_columns:
    # Get the unique values from the original column
    unique_values = df_filtered[column].unique()

    # Create a dictionary where the unique value is the key and the One-Hot vector is the value
    value_encoding_dict = {}
    for val in unique_values:
        # Find the index of the unique value in the original column
        indices = df_filtered.index[df_filtered[column] == val].tolist()
        # Get the corresponding One-Hot encoded vectors
        encoding_vector = encoded_df.iloc[indices].mean(axis=0).tolist()  # Use the mean to represent the encoding vector
        value_encoding_dict[str(val)] = encoding_vector

    # Store this dictionary in the main dictionary under the feature name
    encoding_dict[column] = value_encoding_dict

# Output the final dictionary
print("One-Hot Encoding Dictionary:")
for key, value in encoding_dict.items():
    print(f"{key}")
